# mosquitto.conf — konfigurasi minimal untuk menjalankan proyek ini
# Letakkan file ini di folder yang sama dengan mosquitto, lalu jalankan:
#   mosquitto -c mosquitto.conf

listener 1883
allow_anonymous true
